name: Build

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint
      run: flake8 .

    - name: Deploy staging
      if: github.repository == 'portier/demo-rp' && github.ref == 'refs/heads/master'
      env:
        SECRET: ${{ secrets.DEPLOY_WEBHOOK_SECRET }}
      run: |
        curl -sS -X POST -H @- https://server.portier.io/webhook <<< "Authorization: Bearer $SECRET"
